// Generated by mobile_tokens.py. Do not edit.
package mobile.tokens

import androidx.compose.runtime.staticCompositionLocalOf

data class MobileTheme(
    val profile: String = "base",
    val values: Map<String, String> = MobileTokens.values(profile),
)

val LocalMobileTheme = staticCompositionLocalOf { MobileTheme() }
